name: Pär Boman
favicon: null
layout_spectrum: 1
typography_spectrum: 1
title: Pär Boman
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffffd'
    - '#06091a'
    - '#294fbe'
    - '#9262c8'
    - '#f97bba'
  brandStrength: 0.6875
  lightness: 0.4532273376826197
  saturation: 0.9336723450105637
  rhythmicContrast: 0.28353926772251725
purpose: []
