name: Pär Boman
favicon: null
layout_spectrum: 0.5215663351118565
typography_spectrum: 0.21322391531430185
title: Pär Boman
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ff0000'
    - '#000000'
    - '#ff5e5f'
    - '#ff9ca1'
    - '#ffd7dc'
  brandStrength: 0.6631617725361139
  lightness: 0.4532273376826197
  saturation: 0.9336723450105637
  rhythmicContrast: 0.28353926772251725
purpose: []
